version: '3'
services:
  cleanup:
    image: alpine:3.8
    command: rm -r app/build/libs
    volumes:
      - .:/app
  gradle:
    image: gradle
    command: gradle build
    working_dir: /home/gradle/project
    volumes:
    - .:/home/gradle/project
    depends_on:
      - cleanup